import "./globals.css";
import type { Metadata } from "next";
import ReactQueryProviders from "./providers/ReactQueryProviders";
import { ToastContainer } from "react-toastify";
import "react-toastify/ReactToastify.min.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-2">
        <ReactQueryProviders>{children}</ReactQueryProviders>
        <ToastContainer />
      </body>
    </html>
  );
}
